### ISSUE TITLE
Simulation with multiple FMUs

### ISSUE THREAD

**Issue by kosmylo** [ucuapps/modelicagym#15]
As I understood by reading the tutorial on how to integrate FMU, it is only possible to use one FMU for control in this framework. My aim is to control a battery model exported as FMU, which is located in a large power network. For this purpose, I need my observation space to include quantities outside of the battery FMU. For example, if my battery is located in a bus with a photovoltaic connected (which is also another FMU) to be able to include its power in the observation space. 

Is something like that possible? Would it be possible with some modifications?

**Comment by OlehLuk** [comment]
Yes, you understood it right. This toolbox was developed for using FMUs in a plug-and-play manner, that is one FMU corresponds to one environment.
One option is to integrate each FMU separately and then combine these into one environment with your code implementing the required custom logic. This way you can avoid making changes in the toolbox itself.
