### ISSUE TITLE
Inconsistent return type in `modelica_base_env`

### ISSUE THREAD

**Issue by dariomangoni** [ucuapps/modelicagym#17]
Hi,
the `step()` function usually returns a tuple which first argument is the state.
The state type turns out to be set, for the default case, by `get_state(result)` of the `do_simulation()` function and it is a tuple (*modelica_base_env@241*).

However, in case the step functions catches a `done()`, then the step function returns a `np.array(self.state)`; thus being different from the previous case.

Am I correct?
And: why returning a tuple instead of an array which is much more comfortable to use? Is it because the FMU might return integers instead of all-reals?

Thanks!

**Comment by OlehLuk** [comment]
Hi,
yes, you are correct. I suggest keeping `numpy.array` type here: https://github.com/ucuapps/modelicagym/pull/20

Unfortunately, it's not possible for me to test this update. So I would be really grateful if you could check that `fix_align_return_type` branch code is functioning properly
