### ISSUE TITLE
Set options["result_handling"] = "memory" as default

### ISSUE THREAD

**Issue by dariomangoni** [ucuapps/modelicagym#18]
Hi,
I would suggest to set `options["result_handling"] = "memory"` as default in `modelica_base_env/do_simulation`.
Writing to disk is a rather expensive operation (my code was running 15x slower because of this) and changing the setting would require overriding the `do_simulation` (I don't see any kwargs that passes such option to the underlying PyFMI `model`, right?)

While for PyFMI was making sense to leave a different default, I think that ModelicaGym users might not be interested in having a variable dump, especially if this comes at such an high performance cost.

**Comment by OlehLuk** [comment]
Hi, thank you very much for the suggestion. This update sounds totally reasonable to me.
It would be great if you created a pull request to the `develop` branch with the suggested changes because I am not sure when will be able to do this important enhancement.

**Comment by dariomangoni** [comment]
Yeah, it might not be game changing, but it might be helpful given the number of calls to the env!
Pull request #19

**Comment by OlehLuk** [comment]
Great thanks for this enhancement!
