### ISSUE TITLE
new setup.py corrent with examples?

### ISSUE THREAD

**Issue by GlennCeusters** [ucuapps/modelicagym#5]
When running from the example dir I get `ModuleNotFoundError: No module named 'gymalgs'`
setup_test is working.
when changed back to ..gymalgs.rl I get 
`    from ..gymalgs.rl import QLearner
ValueError: attempted relative import beyond top-level package`
can load modelicagym.gymalgs.rl but then I get `ModuleNotFoundError: No module named 'examples'` somewhere down the line

**Comment by GlennCeusters** [comment]
the later `ModuleNotFoundError: No module named 'examples'` is due to the wrong entry_point `entry_point='examples:JModelicaCSCartPoleEnv',` as examples no longer is part of the package (setup.py)

**Comment by OlehLuk** [comment]
Thank you for pointing this out. Such an output is reproducible, but expected. So, there is a need in corresponding updates in docs. 
First of all, running examples is expected without *modelicagym* package installation. To run *cart_pole_q_learner.py* one just has to clone the repo. Second, the advised way to run examples is with PyCharm IDE. It automatically adds project root to the PYTHONPATH.

If one wants to run example from the command line, they should update PYTHONPATH with project root:
```bash
:<work_dir>$ git clone https://github.com/ucuapps/modelicagym.git
:<work_dir>$ export PYTHONPATH=$PYTHONPATH:<work_dir>/modelicagym
:<work_dir>$ cd modelicagym/examples
:<work_dir>/modelicagym/examples $ python cart_pole_q_learner.py
```

**Comment by OlehLuk** [comment]
Updated docs with proper instructions for running examples
